name: POI-API-CD

on:
  workflow_run:
    workflows:
      - "POI-API-CI"
    types:
      - "completed"
  push:
    branches: [ main ]
    paths:
      - ".github/workflows/poi-api-dotnet-cd.yml"
  pull_request:
    branches: [ main ]
    paths:
      - ".github/workflows/poi-api-dotnet-cd.yml"

jobs:
  staging-deploy:
  #    if: ${{ github.event.workflow_run.conclusion == 'success' }}  #1234
    uses: marceloes/openhack-devops-team/.github/workflows/deploy-container-webapp.yml@main
    with:
      filepath: "apis/poi/web"
      imagename: "devopsoh/api-poi"
      acrname: "openhack4ue1whv5acr"
      webappname: "openhack4ue1whv5poi"
      slotname: staging
    secrets:
      azurecreds: ${{ secrets.AZURE_CREDS }}
  
  production-deploy:
    needs: staging-deploy
    uses: marceloes/openhack-devops-team/.github/workflows/slot-swap.yml@main
    with:
      webappname: "openhack4ue1whv5poi"
      resourcegroup: openhack4ue1whv5rg
      sourceslotname: staging
      targetslotname: production
    secrets:
      azurecreds: ${{ secrets.AZURE_CREDS }}
    
    

