name: POI-API-CD

on:
#  workflow_run:
#    workflows:
#      - "POI-API-CI"
#    types:
#      - "completed"
  push:
    branches: [ main ]
    paths:
      - ".github/workflows/poi-api-dotnet-cd.yml"
  pull_request:
    branches: [ main ]
    paths:
      - ".github/workflows/poi-api-dotnet-cd.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      ACRNAME: "openhack4ue1whv5acr"
      IMAGE_NAME: "devopsoh/api-poi"

#    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:

    - uses: actions/checkout@v2

    - uses: Azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDS }}

    - name: Azure ACR build image CLI Action
      uses: Azure/cli@1.0.4
      with:
        # <Azure Container Registry URI>/<ACR_repository_name>:<Revision Number> where the ACR_repository_name follows the naming convention devopsoh/<image_name>:<tag>.
        inlineScript: |
          cd apis/poi/web
          echo $PWD
          ls -a
          az acr build --image "${{ env.IMAGE_NAME }}:${{ github.sha }}" --registry ${{ env.ACRNAME }}  .

    - name: Azure WebApp Deploy
      uses: Azure/webapps-deploy@v2
      with:
        # Name of the Azure Web App
        app-name: "openhack4ue1whv5poi"
        # Applies to Web Apps(Windows and Linux) and Web App Containers(linux). Multi container scenario not supported. Publish profile (*.publishsettings) file contents with Web Deploy secrets
        #publish-profile: # optional
        # Enter an existing Slot other than the Production slot
        slot-name: staging # optional, default is production
        # Applies to Web App only: Path to package or folder. *.zip, *.war, *.jar or a folder to deploy
        #package: # optional, default is .
        # Applies to Web App Containers only: Specify the fully qualified container image(s) name. For example, 'myregistry.azurecr.io/nginx:latest' or 'python:3.7.2-alpine/'. For multi-container scenario multiple container image names can be provided (multi-line separated)
        images: ${{ env.ACRNAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }}
        # Applies to Web App Containers only: Path of the Docker-Compose file. Should be a fully qualified path or relative to the default working directory. Required for multi-container scenario
        #configuration-file: # optional
        # Enter the start up command. For ex. dotnet run or dotnet run
        #startup-command: # optional

