name: POI-API-CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: ['dev*' ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ '3.1.x', '5.0' ]

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup dotnet core version ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
    
    - name: Restore dependencies
      run: dotnet restore apis/poi/poi.sln
    
    - name: Build project
      run: dotnet build --no-restore apis/poi/poi.sln
    
    - name: Test projects
      run: dotnet test --no-build --verbosity normal apis/poi/tests/UnitTests/UnitTests.csproj
