name: TRIPS-API-GO-CD

on:
#  workflow_run:
#    workflows:
#      - "POI-API-CI"
#    types:
#      - "completed"
  push:
    branches: [ main ]
    paths:
      - ".github/workflows/trips-api-go-cd.yml"
  pull_request:
    branches: [ main ]
    paths:
      - ".github/workflows/trips-api-go-cd.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      ACRNAME: "openhack4ue1whv5acr"

#    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:

    - uses: actions/checkout@v2

    - uses: Azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDS }}

    - name: Azure ACR build image CLI Action
      uses: Azure/cli@1.0.4
      with:
        # <Azure Container Registry URI>/<ACR_repository_name>:<Revision Number> where the ACR_repository_name follows the naming convention devopsoh/<image_name>:<tag>.
        inlineScript: |
          cd apis/trips
          echo $PWD
          ls -a
          az acr build --image "devopsoh/api-trips:${{ github.run_number }}" --registry ${{ env.ACRNAME }}  .
