name: TRIPS-API-CI

on:
  push:
    branches: [ 'main' ]
    paths:
      - "apis/trips/tripsgo/**"
      - ".github/**"
  pull_request:
    branches: [ 'main' ]
    paths:
      - "apis/trips/tripsgo/**"
      - ".github/**"

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apis/trips/tripsgo

    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.8

    - uses: Azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDS }}

    - uses: Azure/get-keyvault-secrets@v1
      with:
        keyvault: "openhack4ue1whv5kv"
        secrets: "SQLDBNAME, SQLPASSWORD, SQLSERVER, SQLUSER"
      id: secretsAction

    - name: Restore
      run: go get 

    - name: Build
      run: go build -v 

    - name: Run
      run: go run ../main.go -v

    - name: Test
      run: go test
      env:
        SQL_USER: ${{ steps.secretsAction.outputs.SQLUSER }} 
        SQL_PASSWORD: ${{ steps.secretsAction.outputs.SQLPASSWORD }} 
        SQL_SERVER: "openhack4ue1whv5sql.database.windows.net" 
        SQL_DBNAME: "mydrivingDB" 
        WEB_PORT: "80" 
        WEB_SERVER_BASE_URI: "http://0.0.0.0" 
        DOCS_URI: "http://localhost" 
        DEBUG_LOGGING: "false" 
        APP_VERSION: "trips default"

