# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: USER-JAVA-CI

on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ]

jobs:
  build:
    env: 
      SQL_USER: "YourUserName"
      SQL_PASSWORD: "changeme" 
      SQL_SERVER: "changeme.database.windows.net" 
      SQL_DBNAME: "mydrivingDB" 
      APP_VERSION: "user-java default" 
    defaults:
        run:
            working-directory: api/user-java  
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        #settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Clean Maven
      run: mvn clean package

    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
    - name: Run tests
      run: mvn clean test

