name: USERJAVA-API-CD

on:
#  workflow_run:
#    workflows:
#      - "POI-API-CI"
#    types:
#      - "completed"
  push:
    branches: [ main ]
    paths:
      - ".github/workflows/user-java-maven-cd.yml"
  pull_request:
    branches: [ main ]
    paths:
      - ".github/workflows/user-java-maven-cd.yml"

jobs:

  staging-deploy:
  #    if: ${{ github.event.workflow_run.conclusion == 'success' }}  #123
    uses: marceloes/openhack-devops-team/.github/workflows/deploy-container-webapp.yml@main
    with:
      filepath: "apis/user-java"
      imagename: "devopsoh/api-user-java"
      acrname: "openhack4ue1whv5acr"
      webappname: "openhack4ue1whv5userjava"
      slotname: staging
    secrets:
      azurecreds: ${{ secrets.AZURE_CREDS }}
  
  production-deploy:
    needs: staging-deploy
    uses: marceloes/openhack-devops-team/.github/workflows/slot-swap.yml@main
    with:
      webappname: "openhack4ue1whv5userjava"
      resourcegroup: openhack4ue1whv5rg
      sourceslotname: staging
      targetslotname: production
    secrets:
      azurecreds: ${{ secrets.AZURE_CREDS }}


